services:
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      USE_REDIS: "true"
      REDIS_ADDR: "redis:6379"
      REDIS_TTL: "30s"
      OIL_INITIAL_PRICE: "78.50"
      PRICE_UPDATE_INTERVAL: "2s"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
